[build]
dist = "../dist"

[serve]
address = "127.0.0.1"
port = 3000

[[hooks]]
stage = "post_build"
command = "sh"
command_arguments = ["-c", "npx tailwindcss -i style.css -o $TRUNK_STAGING_DIR/style.css"]
